require('dotenv').config()

export const environment = {
  API_BASE_END_POINT: process.env.REACT_APP_API_BASE_END_POINT,
  ZOHO_LOGIN_REDIRECT_URI: process.env.REACT_APP_ZOHO_LOGIN_REDIRECT_URI,
  MOBILE_LOGIN_URL: process.env.REACT_APP_MOBILE_URL,
  PUSHER_BEAM_INSTANCE_ID: process.env.REACT_APP_PUSHER_BEAM_INSTANCE_ID,
  PUSHER_ID: process.env.REACT_APP_PUSHER_ID
};
